import os,sys
rsfroot = os.environ.get('RSFROOT') + '/'
rsfsrc  = os.environ.get('RSFSRC') + '/'

# 🔧 CHANGED: use rsfsrc instead of rsfroot so it can find api/c/SConstruct
SConscript(rsfsrc + 'api/c/SConstruct', must_exist=False)

sys.path.append(rsfsrc + 'framework')
import bldutil
env = bldutil.Debug()

# Add OpenMP support for parallel execution
env.Append(CCFLAGS=['-fopenmp'])
env.Append(LINKFLAGS=['-fopenmp'])

# Add MPI support (optional - uncomment if you have MPI)
# env['CC'] = 'mpicc'
# env.Append(CCFLAGS=['-DMPI'])

# 🔧 CHANGED: link against rsf (Madagascar), not su
env.Append(
    LIBS=[env.get('DYNLIB','')+'rsf', env.get('DYNLIB','')+'m'],
    CPPPATH=[rsfroot+'include'],
    LIBPATH=[rsfroot+'lib']
)

#
# C mains
#
glob_build = False
bindir = libdir = pkgdir = None
targets = bldutil.UserSconsTargets()
targets.c = \
'''
AFDM
EFDM
'''

targets.build_all(env, glob_build, rsfsrc, bindir, libdir, pkgdir)  # optional: rsfsrc safer than rsfroot
